apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: 348096830755.dkr.ecr.us-east-2.amazonaws.com/tagit:config_1
          ports:
            - containerPort: 8091
